### ISSUE TITLE
Link from htslib.org site to hts-specs link

### ISSUE THREAD

**Issue by cmdcolin** [samtools/www.htslib.org#27]
Clicking on htslib.org -> specifications gives basically not the stuff in this repo http://www.htslib.org/doc/#file-formats

Can we make it link to  https://samtools.github.io/hts-specs/

**Comment by jkbonfield** [comment]
I punted this issue to the www.htslib.org repository.

Agreed it could do with updating, although they contain different information.  www.htslib.org also contains various citations.  Arguably these should be in the hts-specs copy, but for now we should add additional text, eg:

Specifications
-----

The specification documents themselves are held in the [hts-specs github repository](https://github.com/samtools/hts-specs/).   Formatted versions of these can be read at https://samtools.github.io/hts-specs/

**Comment by jmarshall** [comment]
That link's already on that very page, just above in the “File formats and plugins” section.

To be sure, maybe it could be bolder. Or the File Formats and Publications :: File Formats sections merged somehow…

**Comment by jkbonfield** [comment]
Ah yes.  In that case it's an issue of the #link which is going to the wrong section maybe (to file-formats-and-plugins instead?).   Although merging is perhaps better.

**Comment by jkbonfield** [comment]
Infact it's my fault: 0ea84bea changed the title of one section.

Previously we had File Formats listed twice so the same #key was duplicated and the menu took us to the first one.  I'll patch index.html.

**Comment by jmarshall** [comment]
Oh, now I see what @cmdcolin specifically meant by “Clicking on htslib.org -> specifications” :smile:

**Comment by jkbonfield** [comment]
Yeah it used to go to the right point.  We could either edit it in index.html and _includes.header.html, or simpler just change doc.md back by removing the "and plugins" bit.  That's rather superfluous.  I didn't fully understand the automatic nature of #keys and the menu items when I did that.

**Comment by jkbonfield** [comment]
Executive decision made :-)

Thanks for the report @cmdcolin
